# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReportGenerator
                                 A QGIS plugin
 produces reports on layers choosen  in different formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-01-01
        git sha              : $Format:%H$
        copyright            : (C) 2024 by COM413 Group 6
        email                : chambakatajoel@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.core import QgsProject , Qgis
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from tabulate import tabulate
from reportlab.platypus import SimpleDocTemplate, Table
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Table, TableStyle
from reportlab.lib import colors


import sqlite3
from tabulate import tabulate


from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction ,QFileDialog ,QTableWidgetItem

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .report_gen_dialog import ReportGeneratorDialog
import os.path


class ReportGenerator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ReportGenerator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Report Gen')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ReportGenerator', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/report_gen/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Export info'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Report Gen'),
                action)
            self.iface.removeToolBarIcon(action)

#select file buttons action
    def select_output_fileTxt(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Select output file ","", '*.txt')
        self.dlg.lineEditTxt.setText(filename)

    def select_output_filePdf(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Select output file ","", '*.pdf')
        self.dlg.lineEditPdf.setText(filename)
    
    def select_output_fileDb(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Select output file ","", '*.db')
        self.dlg.lineEditDb.setText(filename)


#export buttons actions
    def onpBExpToTxtClicked(self):
            print('exported to txt')
            layers = QgsProject.instance().layerTreeRoot().children()
            filename = self.dlg.lineEditTxt.text()
            with open(filename, 'w') as output_file:
                selectedLayerIndex = self.dlg.comboBox.currentIndex()
                selectedLayer = layers[selectedLayerIndex].layer()
                fieldnames = [field.name() for field in selectedLayer.fields()]
                # write header
                line = tabulate([], headers=fieldnames)
                output_file.write(line + '\n')
                # write feature attributes
                for f in selectedLayer.getFeatures():
                    values = [f[name] for name in fieldnames]
                    line = tabulate([values], tablefmt="plain")  # Wrap values in a list
                    output_file.write(line + '\n')

                self.iface.messageBar().pushMessage(
                "Success", "Output text file written at " + filename,
                level=Qgis.Success, duration=3)
    
    def onpBExpToPDFClicked(self):
        print('exported to PDF')
        layers = QgsProject.instance().layerTreeRoot().children()
        filename = self.dlg.lineEditPdf.text()
        doc = SimpleDocTemplate(filename, pagesize=letter)
        elements = []
        selectedLayerIndex = self.dlg.comboBox.currentIndex()
        selectedLayer = layers[selectedLayerIndex].layer()
        fieldnames = [field.name() for field in selectedLayer.fields()]
        styles = getSampleStyleSheet()
        data = [[Paragraph('<b>{}</b>'.format(field), styles['Normal']) for field in fieldnames]]  # Start with the header
        for f in selectedLayer.getFeatures():
            values = [f[name] for name in fieldnames]
            data.append(values)  # Add each row to the data
        table = Table(data)
        table.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke)]))
        
        elements.append(table)
        doc.build(elements)
        

        self.iface.messageBar().pushMessage(
            "Success", "Output pdf file written at " + filename,
            level=Qgis.Success, duration=3)

    def onpBExpToDBClicked(self):
            print('exported to database')
            layers = QgsProject.instance().layerTreeRoot().children()
            filename = self.dlg.lineEditDb.text()
            conn = sqlite3.connect(filename)
            c = conn.cursor()

            selectedLayerIndex = self.dlg.comboBox.currentIndex()
            selectedLayer = layers[selectedLayerIndex].layer()
            fieldnames = [field.name() for field in selectedLayer.fields()]

            # create table
            c.execute(f"CREATE TABLE data ({', '.join(fieldnames)})")

            # insert data
            for f in selectedLayer.getFeatures():
                values = [str(f[name]) for name in fieldnames]
                c.execute(f"INSERT INTO data VALUES ({', '.join('?' for _ in values)})", values)

            conn.commit()
            conn.close()
            
            self.iface.messageBar().pushMessage(
                "Success", "Output Database file written at " + filename,
                level=Qgis.Success, duration=3)


    def run(self):
       
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ReportGeneratorDialog()

            self.dlg.pBtnFileTxt.clicked.connect(self.select_output_fileTxt)
            self.dlg.pBtnFilePdf.clicked.connect(self.select_output_filePdf)
            self.dlg.pBtnFileDb.clicked.connect(self.select_output_fileDb)

            self.dlg.pBExpToTxt.clicked.connect(self.onpBExpToTxtClicked)
            self.dlg.pBExpToPDF.clicked.connect(self.onpBExpToPDFClicked)
            self.dlg.pBExpToDB.clicked.connect(self.onpBExpToDBClicked)


        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox.addItems([layer.name() for layer in layers])

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            pass